apiVersion: apps/v1
kind: Deployment
metadata:
  name: publish
  labels:
    app: publish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publish
  template:
    metadata:
      labels:
        app: publish
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: publish
          image: aivleai08project.azurecr.io/publish:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: TZ
              value: Asia/Seoul
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8084
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8084
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

