apiVersion: v1
kind: Service
metadata:
  name: publish
spec:
  selector:
    app: publish
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP  # 내부용. 외부 노출하려면 NodePort or LoadBalancer
