apiVersion: apps/v1
kind: Deployment
metadata:
  name: writing
  labels:
    app: writing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writing
  template:
    metadata:
      labels:
        app: writing
    spec:
      containers:
        - name: writing
          image: aivleai08project.azurecr.io/writing:v1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_KAFKA_BINDER_BROKERS
              value: my-kafka:9092
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              value: my-kafka:9092
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: my-kafka:9092
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8081
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
