# 공통 설정
server:
  port: 8080            # 로컬 기본 포트

spring:
  application:
    name: writing

# -------- default 프로필 (로컬 개발) --------
---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:writing
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        event-in:
          group: writing
          destination: creatorplatform
          contentType: application/json
        event-out:
          destination: creatorplatform
          contentType: application/json

authors:
  url: http://localhost:8081   # 임시 계정 서비스 주소

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

# -------- docker 프로필 --------
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/writing
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
      bindings:
        event-in:
          group: writing
          destination: creatorplatform
          contentType: application/json
        event-out:
          destination: creatorplatform
          contentType: application/json

authors:
  url: http://account:8081     # 도커 네트워크상의 계정 MS
