# // creator-platform/writing/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: writing

# -------- default --------
---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:writing
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        event-in:
          group: writing
          destination: creatorplatform
          content-type: application/json
        event-out:
          destination: creatorplatform
          content-type: application/json

authors:
  url: http://localhost:8081

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

# -------- docker --------
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/writing
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:29092
      bindings:
        event-in:
          group: writing
          destination: creatorplatform.completed-publication
          content-type: application/json   # ✅ kebab-case
        event-out:
          destination: creatorplatform
          content-type: application/json

authors:
  url: http://account:8081
